# Generated by Django 4.2 on 2024-08-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pegawai', '0009_alter_pegawaikoordinatorsubstansi_akhir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersayaratanLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persayaratan', to='layanan.layanan')),
            ],
        ),
        migrations.CreateModel(
            name='PengajuanLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengajuan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Diajukan', 'Diajukan'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='Diajukan', max_length=20)),
                ('file_persyaratan', models.FileField(blank=True, null=True, upload_to='pengajuan_files/')),
                ('layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to='layanan.layanan')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan', to='pegawai.pegawai')),
            ],
        ),
    ]
