# Generated by Django 4.2 on 2024-08-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersyaratanLayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PersayaratanLayanan',
        ),
        migrations.AddField(
            model_name='layanan',
            name='persyaratan',
            field=models.ManyToManyField(blank=True, related_name='layanans', to='layanan.persyaratanlayanan'),
        ),
    ]
