# Generated by Django 4.2 on 2024-08-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0002_persyaratanlayanan_delete_persayaratanlayanan_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='layanan',
            table='mapeg_layanan',
        ),
        migrations.AlterModelTable(
            name='pengajuanlayanan',
            table='mapeg_pengajuan_layanan',
        ),
        migrations.AlterModelTable(
            name='persyaratanlayanan',
            table='mapeg_persayaratan_layanan',
        ),
    ]
