# Generated by Django 4.2 on 2024-08-27 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0003_alter_layanan_table_alter_pengajuanlayanan_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanLayananFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pengajuan_files/')),
                ('pengajuan_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='layanan.pengajuanlayanan')),
                ('persyaratan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_files', to='layanan.persyaratanlayanan')),
            ],
        ),
    ]
