# Generated by Django 4.2 on 2024-10-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0004_pengajuanlayananfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layanan',
            name='deskripsi',
        ),
    ]
