# Generated by Django 4.2 on 2024-10-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan', '0005_remove_layanan_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='layanan',
            name='waktu_mulai',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='layanan',
            name='waktu_selesai',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
