# Generated by Django 4.2 on 2024-06-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('koordinator_substansi', '0003_rename_koordinatorsubstansiid_koordinatorsubstansi_koorsub_id'),
        ('unit_kerja', '0006_alter_subunitkerja_table_alter_unitkerja_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PangkatGolongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pangkat', models.CharField(max_length=255)),
                ('golongan', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'mapeg_pangkat_golongan',
                  'managed': False,  # Add this line
            },
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('koordinator_substansi', models.ManyToManyField(blank=True, related_name='pegawai_koordinator_substansi', to='koordinator_substansi.koordinatorsubstansi')),
                ('pangkat_golongan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pegawai.pangkatgolongan')),
                ('sub_unit_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit_kerja.subunitkerja')),
                ('unit_kerja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit_kerja.unitkerja')),
            ],
            options={
                'db_table': 'mapeg_pegawai',
                'managed': False
            },
        ),
        migrations.CreateModel(
            name='PegawaiKoordinatorSubstansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmt', models.DateField()),
                ('akhir', models.DateField()),
                ('status', models.BooleanField()),
                ('koordinator_substansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='koordinator_substansi.koordinatorsubstansi')),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pegawai.pegawai')),
            ],
            options={
                'db_table': 'mapeg_pegawai_koorsub',
                'unique_together': {('pegawai', 'koordinator_substansi')},
                  'managed': False,  # Add this line
            },
        ),
    ]
