# Generated by Django 4.2 on 2024-06-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pangkatgolongan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pegawai',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pegawaikoordinatorsubstansi',
            options={},
        ),
    ]
