# Generated by Django 4.2 on 2024-06-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_alter_pangkatgolongan_options_alter_pegawai_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pegawaikoordinatorsubstansi',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pegawai',
            name='koordinator_substansi',
        ),
    ]
