# Generated by Django 4.2 on 2024-06-28 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koordinator_substansi', '0003_rename_koordinatorsubstansiid_koordinatorsubstansi_koorsub_id'),
        ('pegawai', '0003_alter_pegawaikoordinatorsubstansi_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pegawaikoordinatorsubstansi',
            unique_together={('pegawai', 'koordinator_substansi')},
        ),
    ]
