# Generated by Django 4.2 on 2024-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0004_alter_pegawaikoordinatorsubstansi_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
