# Generated by Django 4.2 on 2024-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0005_alter_pegawai_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaikoordinatorsubstansi',
            name='akhir',
            field=models.DateField(null=True),
        ),
    ]
