# Generated by Django 4.2 on 2024-07-03 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0006_alter_subunitkerja_table_alter_unitkerja_table'),
        ('pegawai', '0006_alter_pegawaikoordinatorsubstansi_akhir'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaikoordinatorsubstansi',
            name='unit_Kerja',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerja'),
        ),
    ]
