# Generated by Django 4.2 on 2024-07-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0007_pegawaikoordinatorsubstansi_unit_kerja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pegawaikoordinatorsubstansi',
            old_name='unit_Kerja',
            new_name='unit_kerja',
        ),
    ]
