# Generated by Django 4.2 on 2024-08-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0006_alter_subunitkerja_table_alter_unitkerja_table'),
        ('pegawai', '0008_rename_unit_kerja_pegawaikoordinatorsubstansi_unit_kerja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaikoordinatorsubstansi',
            name='akhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawaikoordinatorsubstansi',
            name='unit_kerja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerja'),
        ),
    ]
