# Generated by Django 4.2 on 2024-06-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitKerja',
            fields=[
                ('UnitKerjaID', models.AutoField(primary_key=True, serialize=False)),
                ('NamaUnitKerja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubUnitKerja',
            fields=[
                ('SubUnitKerjaID', models.AutoField(primary_key=True, serialize=False)),
                ('NamaSubUnitKerja', models.CharField(max_length=255)),
                ('UnitKerjaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerja')),
            ],
        ),
    ]
