# Generated by Django 4.2 on 2024-06-19 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunitkerja',
            name='UnitKerjaID',
        ),
        migrations.CreateModel(
            name='UnitKerja_SubUnitKerja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SubUnitKerjaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.subunitkerja')),
                ('UnitKerjaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.unitkerja')),
            ],
            options={
                'unique_together': {('UnitKerjaID', 'SubUnitKerjaID')},
            },
        ),
    ]
