# Generated by Django 4.2 on 2024-06-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0003_rename_namasubunitkerja_subunitkerja_nama_sub_unit_kerja_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unitkerja_subunitkerja',
            table='mapeg_unit_kerja_subunit',
        ),
    ]
