# Generated by Django 4.2 on 2024-06-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0004_alter_unitkerja_subunitkerja_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subunitkerja',
            table='mapeg__subunit',
        ),
        migrations.AlterModelTable(
            name='unitkerja',
            table='mapeg__unit_kerja',
        ),
    ]
