# Generated by Django 4.2 on 2024-06-23 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0005_alter_subunitkerja_table_alter_unitkerja_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subunitkerja',
            table='mapeg_subunit',
        ),
        migrations.AlterModelTable(
            name='unitkerja',
            table='mapeg_unit_kerja',
        ),
    ]
