# Generated by Django 4.2 on 2024-06-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoordinatorSubstansi',
            fields=[
                ('KoordinatorSubstansiID', models.AutoField(primary_key=True, serialize=False)),
                ('NamaKoordinatorSubstansi', models.CharField(max_length=255)),
            ],
        ),
    ]
