# Generated by Django 4.2 on 2024-06-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unit_kerja', '0002_remove_subunitkerja_unitkerjaid_and_more'),
        ('koordinator_substansi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koordinatorsubstansi',
            old_name='NamaKoordinatorSubstansi',
            new_name='nama',
        ),
        migrations.AddField(
            model_name='koordinatorsubstansi',
            name='sub_unit_kerja',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit_kerja.subunitkerja'),
        ),
    ]
