# Generated by Django 4.2 on 2024-06-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koordinator_substansi', '0002_rename_namakoordinatorsubstansi_koordinatorsubstansi_nama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='koordinatorsubstansi',
            old_name='KoordinatorSubstansiID',
            new_name='koorsub_id',
        ),
    ]
