# Generated by Django 4.2 on 2024-08-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koordinator_substansi', '0003_rename_koordinatorsubstansiid_koordinatorsubstansi_koorsub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='koordinatorsubstansi',
            name='tingkat',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
